[build]
  # This will be run the site build
  command = ""
  # This is the directory is publishing to netlify's CDN
  publish = "public"
  # Location of built function code
  functions = "functions-build"